apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-gitops
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx-hello-gitops

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-hello-gitops
spec:
  ingressClassName: nginx
  rules:
    - host: demo-gitops.{CLUSTER_IP}.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-hello-gitops
                port:
                  number: 80