apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeinvaders
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://lucky-sideburn.github.io/helm-charts/
    chart: kubeinvaders
    targetRevision: 1.9.8
    helm:
      values: |
        ingress:
          enabled: true
          className: nginx
          hostName: kubeinvaders-gitops.209.38.112.61.nip.io 
        service:
          type: ClusterIP
        config:
          target_namespace: basic-depoly
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeinvaders
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
