apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeinvaders
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lucky-sideburn/KubeInvaders
    targetRevision: main
    path: helm
    helm:
      values: |
        service:
          type: LoadBalancer
        route_host: kubeinvaders.local
        namespace_regexp: ^default$
        target_namespace: "default"
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeinvaders
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true